language: node_js
node_js:
  - 15.14.0
dist: focal
sudo: required
git:
  depth: 3

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
before_install:
    - sudo apt-get install -y nodejs
    - npm install -g npm@7.7.6

install:
  - npm install
before_script:
  - npm run eslint
  - npm run test
  - npm run coverage
script:
  - npm run build
